config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'articles/new',      to: 'articles#new'
  post 'articles',         to: 'articles#create'
  get 'articles/:id/edit', to: 'articles#edit', as: :edit_article
  patch 'articles/:id',    to: 'articles#update'
  get 'articles',          to: 'articles#index'
  get 'articles/:id',      to: 'articles#show', as: :article

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save

    redirect_to article_path(@article)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    redirect_to article_path(@article)
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<div class="container">
  <h2>Edit article</h2>

    <%= form_for(@article) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :content %>
    <%= f.text_field :content %>
    <%= f.submit %>
  <% end %>

</div>

app/views/articles/index.html.erb
<div class="container">
    <ul>
      <% @articles.each do |article| %>
        <p>
          <li class="title"><%= link_to article.title, article_path(article.id) %></li>
          <li class="content"><%= article.content %></li>
        </p>
      <% end %>
    </ul>

</div>

app/views/articles/new.html.erb
<div class="container">
  <h2>New article</h2>

    <%= form_for(@article) do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= f.label :content %>
      <%= f.text_field :content %>
      <%= f.submit %>
    <% end %>

<%= link_to "Back", articles_path %>

</div>

app/views/articles/show.html.erb
<div class="container">
  <div id="title">
    <h2><%= @article.title %></h2>
    <div class="edit">
    <%= link_to "Edit", edit_article_path(@article) %>
  </div>
  </div>
  <div id="content">
    <p><%= @article.content %></p>
  </div>

  <%= link_to "Back", articles_path %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="navbar">
      <div class="container-navbar">
        <div class="logo">
         <a href="#">Wikinimous</a>
        </div>
        <div class="new-article">
          <%= link_to "New Article", articles_new_path %>
        </div>
      </div>
    </div>
    <%= yield %>
  </body>
</html>